# Generated by Django 5.1.1 on 2024-10-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_playhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='playhistory',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='playhistory',
            name='store_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
