# Generated by Django 5.1.1 on 2024-10-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_playhistory_name_playhistory_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='store_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
