# Generated by Django 5.1.1 on 2024-10-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='message',
        ),
        migrations.AddField(
            model_name='announcement',
            name='audio_file',
            field=models.FileField(default=1, upload_to='uploads/announcements/'),
            preserve_default=False,
        ),
    ]
