# Generated by Django 5.1.1 on 2024-10-07 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_remove_announcement_message_announcement_audio_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='store_name',
        ),
        migrations.AddField(
            model_name='announcement',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='stores',
            field=models.ManyToManyField(related_name='announcements', to='music.store'),
        ),
    ]
